### ISSUE TITLE
One to many suggestion

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [RobIsInSchool/habil#2]
Hi @RobIsInSchool 

Just took a quick look at your repo (I was making sure I hadn't missed a week 5 issue).

If you have a set for the one to many relationship: https://github.com/RobIsInSchool/habil/blob/7cdc9e23bf16d029f1bcf32ae4deabd8a3073fc1/src/main/java/com/radams/entity/User.java#L61-L62

you do not need the id column here: 

https://github.com/RobIsInSchool/habil/blob/7cdc9e23bf16d029f1bcf32ae4deabd8a3073fc1/src/main/java/com/radams/entity/User.java#L51-L53

In the demo, the User only has an instance variable for the set of Orders, but no Order_id column. https://github.com/mad-java-ent-s21/user-display-demo-code/blob/hibernate-one-to-many-demo/src/main/java/edu/matc/entity/User.java. 

Hope that helps!

**Comment by RobIsInSchool** [comment]
Thanks so much for taking a look at that @pawaitemadisoncollege ! I'll keep this in mind for what I'm about to do.

I realized late yesterday that my problem all along was that I had confused the direction of the one-to-many. I was treating the role entity as the 'many' side when it's actually the 'one' side! 

But I've gotten my wires crossed so many times with this concept, I think I'm going to spend today tearing it all down and trying it again from scratch :(

**Comment by pawaitemadisoncollege** [comment]
Actually for the purposes using tomcat authentication in this class, the user **is** the one side and role is the many side.

One user can have many roles, where a row on the role column will have at minimum: id, user name, role name. Username is the tie back to the user table, but you could also have the user id on the role table as the foreign key.
